### PR TITLE
peek_nth

### PR DESCRIPTION
**Pull request by mattfeusner**
Uses new option in g-speak 4.5's peek command to peek starting at a
specified index, not just the latest one.

### CODE REVIEW

**Comment by sandover** [comment]
Are you considering this assigned to me or yourself @mattfeusner ?

**Comment by mattfeusner** [comment]
I say let's merge it! I don't seem to have permissions to change anything

**Comment by sandover** [comment]
OK, can you make the let/var change first?

**Comment by mattfeusner** [comment]
updated and pushed

**Pull request merged**
