### PR TITLE
Make tests more deterministic

### PR DESCRIPTION
**Pull request by tomjakubowski**
* empty_pool was being called without waiting for the p-stop and
  p-create processes to finish.  As a kludge (and because these are just
  tests), switch to use `spawnSync`. (nb: `spawnSync` was only added in
  v0.11.12, so if we need to support older Node versions I can rewrite
  that).
* Use constants for pool names to avoid confusion.
* The "poke" calls to deposit proteins into a pool weren't guaranteed to
  deposit in the expected order.  Fix this by using a chain of promises
  to serialize the writes to and spawns of the poke processes.

Unfortunately, the oldestIndex and newestIndex tests are broken on my
machine for reasons I don't understand.  The functions work just fine in
a Node REPL, but under the tests it seems like the stdout of
p-oldest-idx/p-newest-idx is closed before any data (i.e. "the index")
is written to them.

### CODE REVIEW

**Comment by tomjakubowski** [comment]
@ebeneliason @BrennanRoberts What version of Node.JS are you using? I introduced a change in this commit that is only supported on v0.11.12 and newer. I noticed that Ubuntu 12.04 ships with something like 0.6.12, is that what you're using (if you are… I'm so sorry.)?

@sandover don't merge until we hear about this

**Comment by ebeneliason** [comment]
We are still shipping on 12.04. I’m not sure if we’re running a newer version of Node.JS—but that’s a question Brennan (who is out this week) is better suited to answer.

**Comment by tomjakubowski** [comment]
It's been confirmed offline that 0.10.40 is the minimum version we need to support.

**Comment by tomjakubowski** [comment]
OK, I rewrote `empty_pool` again to be "asynchronous" and return a promise, which is fulfilled after p-stop and p-create processes finish (regardless of their success/failure). This should be ready for review/merge now.

**Comment by sandover** [comment]
gah, can you resubmit?

**Comment by tomjakubowski** [comment]
This landed in #14 , closing

**Pull request closed without merging**
