### PR TITLE
Fix peek test

### PR DESCRIPTION
**Pull request by BrennanRoberts**
Fixes https://github.com/Oblong/plasma-js-bridge/issues/1

### CODE REVIEW

**Comment by tomjakubowski** [comment]
I'm seeing a test failure:

```
> make test

./node_modules/.bin/mocha --harmony --reporter spec


  poke()
    ✓ pokes a protein
JS-YAML: unknown tag !<tag:oblong.com,2009:slaw/protein> at line 8, column 11:
      key: val
              ^
    ✓ peeks it back in (128ms)
JS-YAML: unknown tag !<tag:oblong.com,2009:slaw/protein> at line 7, column 11:
      key: val
              ^
    1) peeks it back in


  2 passing (149ms)
  1 failing

  1) poke() peeks it back in:
     Error: done() called multiple times
      at Suite.<anonymous> (test/index.js:18:3)
      at Object.<anonymous> (test/index.js:10:1)
      at Array.forEach (native)
      at node.js:951:3
```

**Comment by tomjakubowski** [comment]
seems like this test is quite racy - the "peek it back in" test can run before the "pokes a protein" poke actually finishes

**Comment by BrennanRoberts** [comment]
Good call.

**Comment by sandover** [comment]
i went ahead and merged these.  i'm all hopped up on halloween candy and going wild.

**Pull request merged**
